name: Build RubyVR Firmware

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.event.pull_request.head.sha || github.ref }}
  cancel-in-progress: true

permissions: write-all

env:
  ZEPHYR_SDK_VERSION: "0.16.9"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      sdk-hash: ${{ steps.generate-vars.outputs.sdk-hash }}
      sdk-revision: ${{ steps.generate-vars.outputs.sdk-revision }}
      repo: ${{ steps.generate-vars.outputs.repo }}
      repo-url: ${{ steps.generate-vars.outputs.repo-url }}
      branch: ${{ steps.generate-vars.outputs.branch }}
      repo-hash: ${{ steps.generate-vars.outputs.repo-hash }}
    steps:
      - name: 🚀 Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'

      - name: 💻 Checkout Repository
        uses: actions/checkout@v4
        with:
          path: zephyr-workspace/SlimeNRF-CI
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: 📟 Generate CI Variables
        id: generate-vars
        run: |
          WEST_FILE="zephyr-workspace/SlimeNRF-CI/west.yml"
          SDK_URL=$(yq -r '.manifest.projects[] | select(.name=="sdk-nrf") | .url' "$WEST_FILE")
          SDK_REVISION=$(yq -r '.manifest.projects[] | select(.name=="sdk-nrf") | .revision' "$WEST_FILE")
          SDK_COMMIT=$(git ls-remote "$SDK_URL" "$SDK_REVISION" | awk '{print $1}')

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            REPO="${{ github.event.pull_request.head.repo.full_name }}"
            REPO_URL="${{ github.event.pull_request.head.repo.clone_url }}"
            BRANCH="${{ github.event.pull_request.head.ref }}"
            REPO_COMMIT="${{ github.event.pull_request.head.sha }}"
          else
            REPO="$GITHUB_REPOSITORY"
            REPO_URL="https://github.com/$GITHUB_REPOSITORY.git"
            BRANCH="${GITHUB_REF#refs/heads/}"
            REPO_COMMIT="$GITHUB_SHA"
          fi
          
          echo "sdk-hash=$SDK_COMMIT" >> "$GITHUB_OUTPUT"
          echo "sdk-revision=$SDK_REVISION" >> "$GITHUB_OUTPUT"
          echo "repo=$REPO" >> "$GITHUB_OUTPUT"
          echo "repo-url=$REPO_URL" >> "$GITHUB_OUTPUT"
          echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"
          echo "repo-hash=$REPO_COMMIT" >> "$GITHUB_OUTPUT"

      - name: 🧰 Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake ninja-build gperf ccache dfu-util device-tree-compiler wget \
            python3-dev python3-pip python3-setuptools python3-venv xz-utils file make gcc libsdl2-dev

      - name: 🪁 Install Zephyr SDK
        run: |
          wget -q https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${{ env.ZEPHYR_SDK_VERSION }}/zephyr-sdk-${{ env.ZEPHYR_SDK_VERSION }}_linux-x86_64_minimal.tar.xz
          tar xf zephyr-sdk-${{ env.ZEPHYR_SDK_VERSION }}_linux-x86_64_minimal.tar.xz -C ~/
          rm zephyr-sdk-${{ env.ZEPHYR_SDK_VERSION }}_linux-x86_64_minimal.tar.xz
          ~/zephyr-sdk-${{ env.ZEPHYR_SDK_VERSION }}/setup.sh -c -t arm-zephyr-eabi

      - name: ♻️ Initialize Zephyr Workspace
        run: |
          python3 -m venv ~/.venv
          echo "$HOME/.venv/bin" >> $GITHUB_PATH
          source ~/.venv/bin/activate
          pip install west ninja
          cd zephyr-workspace
          west init -l SlimeNRF-CI
          west update --narrow -o=--depth=1
          west zephyr-export
          pip install -r zephyr/scripts/requirements.txt

      - name: 📥 Clone SlimeVR-Tracker-nRF
        run: |
          cd zephyr-workspace
          git clone --filter=blob:none "${{ steps.generate-vars.outputs.repo-url }}" SlimeVR-Tracker-nRF
          cd SlimeVR-Tracker-nRF
          git checkout "${{ steps.generate-vars.outputs.repo-hash }}"

      - name: 📦 Cache Build Environment
        uses: actions/cache/save@v4
        with:
          path: |
            ~/zephyr-sdk-${{ env.ZEPHYR_SDK_VERSION }}
            ~/.venv
            zephyr-workspace
          key: full-env-${{ steps.generate-vars.outputs.repo-hash }}

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        boards: [
                  {boardname: "promicro_uf2/nrf52840/i2c", fileformat: "uf2", filename: "SlimeNRF_ProMicro_I2C_Tracker"},
                  {boardname: "promicro_uf2/nrf52840/spi", fileformat: "uf2", filename: "SlimeNRF_ProMicro_SPI_Tracker"},
                  {boardname: "promicro_uf2/nrf52840/smspi", fileformat: "uf2", filename: "SlimeNRF_ProMicro_smSPI_Tracker"},
                  {boardname: "promicro_uf2/nrf52840/chrysalis", fileformat: "uf2", filename: "SlimeNRF_ProMicro_Chrysalis_Tracker"},
                  {boardname: "xiao_ble/nrf52840", fileformat: "uf2", filename: "SlimeNRF_XIAO_Tracker"},
                  {boardname: "xiao_ble/nrf52840/sense", fileformat: "uf2", filename: "SlimeNRF_XIAO_Sense_Tracker"},
                  {boardname: "slimenrf_r1/nrf52840", fileformat: "hex", filename: "SlimeNRF_slimenrf_r1_Tracker"},
                  {boardname: "slimenrf_r2/nrf52832", fileformat: "hex", filename: "SlimeNRF_slimenrf_r2_Tracker"},
                  {boardname: "slimenrf_r3/nrf52840/uf2", fileformat: "uf2", filename: "SlimeNRF_slimenrf_r3_Tracker"},
                  {boardname: "slimevrmini_p1_uf2/nrf52833", fileformat: "uf2", filename: "SlimeNRF_slimevrmini_p1_Tracker"},
                  {boardname: "slimevrmini_p2_uf2/nrf52833", fileformat: "uf2", filename: "SlimeNRF_slimevrmini_p2_Tracker"},
                  {boardname: "slimevrmini_p3r6_uf2/nrf52833", fileformat: "uf2", filename: "SlimeNRF_slimevrmini_p3_r6_Tracker"},
                  {boardname: "slimevrmini_p3r7_uf2/nrf52833", fileformat: "uf2", filename: "SlimeNRF_slimevrmini_p3_r7_Tracker"},
                  {boardname: "slimevrmini_p4_uf2/nrf52833", fileformat: "uf2", filename: "SlimeNRF_slimevrmini_p4r8_Tracker"},
                  {boardname: "slimevrmini_p4r9_uf2/nrf52833", fileformat: "uf2", filename: "SlimeNRF_slimevrmini_p4r9_Tracker"},
                  {boardname: "slimevrmini_p4r11_uf2/nrf52833", fileformat: "uf2", filename: "SlimeNRF_slimevrmini_p4r11_Tracker"},
                  {boardname: "nrf52dk/nrf52832", fileformat: "hex", filename: "SlimeNRF_nRF52dk_Tracker"},
                  {boardname: "nrf52840dk/nrf52840", fileformat: "hex", filename: "SlimeNRF_nRF52840dk_Tracker"},
                ]
    steps:
      - name: 🚀 Maximize Build Space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 5120
          swap-size-mb: 1024
          remove-dotnet: 'true'
          remove-android: 'true'

      - name: 📦 Restore Build Environment
        uses: actions/cache/restore@v4
        with:
          path: |
            ~/zephyr-sdk-${{ env.ZEPHYR_SDK_VERSION }}
            ~/.venv
            zephyr-workspace
          key: full-env-${{ needs.setup.outputs.repo-hash }}
          fail-on-cache-miss: true

      - name: 🔨 Build Firmware - ${{ matrix.boards.filename }}
        run: |
          echo "$HOME/.venv/bin" >> $GITHUB_PATH
          source ~/.venv/bin/activate
          cd zephyr-workspace
          west build \
              --board ${{ matrix.boards.boardname }} \
              --pristine=always "SlimeVR-Tracker-nRF" \
              --build-dir "build_${{ matrix.boards.filename }}" \
              -- \
              -DNCS_TOOLCHAIN_VERSION=NONE \
              -DBOARD_ROOT=../"SlimeVR-Tracker-nRF"

      - name: 💾 Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.boards.filename }}
          path: zephyr-workspace/build_${{ matrix.boards.filename }}/zephyr/zephyr.${{ matrix.boards.fileformat }}
